"""
Script for extracting NMR shielding values 
from .magres files generated by CASTEP

Generates line plot of all shifts

Comment out H or C as necessary
"""
from magres.atoms import MagresAtoms
import matplotlib.pyplot as plt
import numpy as np
import csv

def load_magres(path):
    atoms = MagresAtoms.load_magres(path)
    return atoms

# Extracts isotopic magnetic shielding and references shifts
def extract_shifts(atom, atoms_data):
    shifts = ['shift']
    shift_labels = ['label']
    if atom == 'C':
        C = atoms_data.species('C')
        for atom in C:
            iso = atom.ms.iso
            ref = 173.14 # MC ref
            #ref = 172.67 # SJR ref
            shift = (ref - iso)
            shifts.append(shift)
            shift_labels.append(str(atom))
            data = dict(zip(shift_labels, shifts))
        return data
    elif atom == 'H':
        H = atoms_data.species('H')
        for atom in H:
                iso = atom.ms.iso
                ref = 29 #H
                shift = (ref - iso)
                shifts.append(shift)
                shift_labels.append(str(atom))
                data = dict(zip(shift_labels, shifts))
        return data
    else:
        print('Invalid atom type')

# Writing shifts to csv
def write_csv(save_csv, data):
    with open(save_csv, mode='w') as dca:
        for key in data.keys():
            dca.write("%s, %s\n" %(key, data[key]))
